service: lambda-wap-with-iceberg

provider:
  name: aws
  memorySize: 3008
  timeout: 900
  ecr:
    images:
      lambdawapimage:
        path: ./
        platform: linux/amd64

functions:
  wap:
    ephemeralStorageSize: 3008
    image:
      name: lambdawapimage
    events:
      - s3:
          bucket: ${env:S3_USER}
          events: s3:ObjectCreated:*

